version: '3.1'
services:
  
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: YES
      MYSQL_DATABASE: trab_final
      MYSQL_USER: lobatoSQL
      MYSQL_PASSWORD: 1234
    ports:
      - 3304:3306
    expose:
      - '3306'
    networks:
      - reidecio_rede

  api:
    build:
      context: ./
      dockerfile: Dockerfile 
    restart: always
    container_name: api_app
    ports:
      - 3001:3001 
    depends_on:
      - db 
    networks:
      - reidecio_rede
    env_file:
      - .env

networks:
  reidecio_rede: